theme: jekyll-theme-minimal

title: Sacha Beniamine

description: |
    <center><img src="self.jpg" width="150"/></center><br/>

    *Chargé de R&D, Bee Buzziness.*

    *Member of the Laboratoire de Linguistique Formelle (LLF), university Paris Diderot.*

    My research in computational linguistics focuses on the study of mophological structure.
    During my PHD, I investigated the complexity of inflexional systems and inflection classes (declensions or conjugations),
    as well as their typological variation.
    I am interested in computational analyses of morphological data which highlight the structure of morphological systems. I see computational tools as an opportunity to rigorously systematize and explicit linguistic work, a solution to study precisely large amounts of data, and a necessary methodological step towards typological investigation.

    I am currently employed as a R&D scientist at [Bee Buzziness] where I work on document analysis and classification. I currently study the inferrence of structured text from PDF documents using deep learning.

    **sbeniamine [at] linguist [dot] univ-paris-diderot [dot] fr**

    [Resume on Linkedin](https://www.linkedin.com/in/sacha-beniamine-0bb023156) -- [Page on the LLF](http://www.llf.cnrs.fr/fr/Gens/Beniamine)
