theme: jekyll-theme-minimal

title: Sacha Beniamine

logo: img/self.jpg

contact: sbeniamine [at] linguist [dot] univ-paris-diderot [dot] fr
sidetext: |
    <p><em>Post-doc at the Max Planck Institute.</em></p>
    <p><em>Member of the Laboratoire de Linguistique Formelle (LLF), university Paris Diderot.</em></p>

extralinks: |
    <li><a href="http://www.llf.cnrs.fr/fr/Gens/Beniamine"><img src="img/llf.jpg" alt="LLF page"/></a></li>
    <li><a href="https://www.linkedin.com/in/sacha-beniamine-0bb023156"><img src="img/lkd.png" alt="Resume on linkedin"/></a></li>
    <li><a href="https://scholar.google.com/citations?user=3dIp6WcAAAAJ"><img src="img/google-scholar.png" alt="google profile"/></a></li>
    <li><a href="https://www.shh.mpg.de/person/101094/25522"><img src="img/maxplanck.png" alt="Max Planck page"/></a></li>