theme: jekyll-theme-minimal

title: Sacha Beniamine

description: |
    <center><img src="self.jpg" width="150"/></center><br/>

    <p><em>Chargé de R&D, Bee Buzziness.</em></p>

    <p><em>Member of the Laboratoire de Linguistique Formelle (LLF), university Paris Diderot.</em></p>

    <p>sbeniamine [at] linguist [dot] univ-paris-diderot [dot] fr</p>

    <a href="https://www.linkedin.com/in/sacha-beniamine-0bb023156">Resume on Linkedin</a> -- <a href="http://www.llf.cnrs.fr/fr/Gens/Beniamine">Page on the LLF</a>
