theme: jekyll-theme-minimal

title: Sacha Beniamine

description: |
    <center><img src="self.jpg" width="150"/></center><br/>

    Phd Student, Université Paris Diderot

    sbeniamine [at] linguist[dot]univ-paris-diderot[dot]fr
