theme: jekyll-theme-minimal

title: Sacha Beniamine

description: |
    <center><img src="self.jpg" width="150"/></center><br/>

    <italic>Chargé de R&D, Bee Buzziness.</italic><br/>

    <italic>Member of the Laboratoire de Linguistique Formelle (LLF), university Paris Diderot.</italic><br/>

    sbeniamine [at] linguist [dot] univ-paris-diderot [dot] fr<br/>

    <a href="https://www.linkedin.com/in/sacha-beniamine-0bb023156">Resume on Linkedin</a> -- <a href="http://www.llf.cnrs.fr/fr/Gens/Beniamine">Page on the LLF</a>
